### ISSUE TITLE
Basic feature to-do

### ISSUE THREAD

**Issue by willpearse** [sylviakinosian/herbarium-data#1]
- [ ] Data entry
  - [ ] (1) Setup meta-framework of "box complete" --> "run checker function" --> "checker function change colour of box"
  - [ ] (2) Fields of data entry to match common Symbiota entries
  - [ ] (9) Drop-down fill-in a la Google Scholar
- [ ] Output
  - [ ] (3) Three buttons: CSV, DarwinCore, Reset. DarwinCore button only for now
  - [ ] (4) CSV output
  - [ ] (5) Reset
- [ ] Labels
  - [ ] (6) Make HTML for what a label should look like
  - [ ] (7) Fill HTML with 'filler' that can be overwritten at run-time
  - [ ] (8) Write hook to 'find-replace' 'filler' text and save output
- [ ] (WILL; after 2) Write checking functions!!!

**Comment by sylviakinosian** [comment]
For the labels: I'm pretty sure that [Maddie's code](https://github.com/wundalous/labelmaker) can be used here. I'm waiting until we have a little bit more of a finished product before contacting her.

**Comment by sylviakinosian** [comment]
- [ ] verify and add -> post method
- [ ] reset -> wipe everything
- [ ] view output -> go to HTML table view
